add_newline = false
format = """\
	$battery\
	$directory\
	$character\
	"""

# Replace the "❯" symbol in the prompt with "→"
[character]      # The name of the module we are configuring is "character"
success_symbol = "[→](bold green)"
error_symbol = "[→](bold red)"

[git_status]
format = "$ahead_behind"
ahead = "⇡${count}"
diverged = "⇡${ahead_count}⇣${behind_count}"
behind = "⇣${count}"

[directory]
style = "bright-black"

# Disable the package module, hiding it from the prompt completely
[package]
disabled = false


