add_newline = false
format = """\
	$battery\
	$directory\
	$character\
	"""

[character]
success_symbol = "[→](bold green)"
error_symbol = "[→](bold red)"

[directory]
style = "bright-black"

[package]
disabled = false

[battery]
full_symbol = ""
charging_symbol = ""
discharging_symbol = ""

[[battery.display]]
threshold = 10
style = "bold red"
